
CREATE TABLE IVAN.COUNTRIES(name VARCHAR2(10));
INSERT INTO IVAN.COUNTRIES (name) VALUES ('UKRAINE');
INSERT INTO IVAN.COUNTRIES (name) VALUES ('GB');
INSERT INTO IVAN.COUNTRIES (name) VALUES ('USA');
INSERT INTO IVAN.COUNTRIES (name) VALUES ('BRAZIL');
COMMIT;
exit;
